# Generated by Django 2.1.7 on 2019-03-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=16)),
                ('mail', models.EmailField(max_length=20)),
                ('wechat', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('timeslot_start', models.DateTimeField(default=None)),
                ('timeslot_stop', models.DateTimeField(default=None)),
                ('threshold_value', models.FloatField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game_name', models.CharField(max_length=32, unique=True)),
                ('duty_user', models.CharField(max_length=32)),
                ('game_region', models.CharField(max_length=16)),
                ('game_alert', models.BooleanField(default=False)),
                ('alert_count', models.IntegerField(max_length=16)),
                ('last_alert_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('whether_alert', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='alertpage.Game')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('mail', models.EmailField(max_length=20)),
                ('program', models.CharField(max_length=16)),
                ('whether_alert', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
